### ISSUE TITLE
Slashes in filenames on Google Drive causes sync error

### ISSUE THREAD

**Issue by moretocome** [nextcloud/external#10]
The title says it all. Whenever someone creates a document on Google Docs that contains a slash ```/``` in the filename, it causes a sync-error in my Nextcloud client. I expect other illegal characters could also produce the same error, but I have only experienced it with slashes.

Login into Drive and changing the file name fixes the error, but maybe some type of escape function should be implemented for illegal file name characters.

NC and External app are both most recent stable versions and the server is a RPI with the latest Raspbian.

**Comment by nickvergessen** [comment]
This app is about adding external sites to the menu.
You seem to talk about the external storage, so please try https://github.com/nextcloud/server/issues

**Comment by moretocome** [comment]
Sorry @nickvergessen, my bad :) I have posted a new issue at the server repo.
