### ISSUE TITLE
Installation lead to User Setting Crash

### ISSUE THREAD

**Issue by ChristopheCubat** [nextcloud/external#100]
### Expected behaviour
Setting of user should appears

### Actual behaviour
Get Error 500

### Server configuration
**Operating system**:
Docker

**Database:**
MariaDb

**Nextcloud version:** 
13

**Bug:**

`{"reqId":"jCfYJCP0qtsIDlI7tWOS","level":3,"time":"2018-05-23T15:03:18+00:00","remoteAddr":"X.X.X.X","user":"admin","app":"index","method":"GET","url":"\/settings\/user","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"id\\\" for route \\\"external.site.showPage\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'external.site.s...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external.site.s...', Array, 1)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('external.site.s...', Array, false)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\CachingRouter->generate('external.site.s...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/custom_apps\\\/external\\\/lib\\\/Settings\\\/Personal.php(60): OC\\\\URLGenerator->linkToRoute('external.site.s...', Array)\\n#5 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(115): OCA\\\\External\\\\Settings\\\\Personal->getForm()\\n#6 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/PersonalSettingsController.php(67): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSettings(Array)\\n#7 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n#8 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#17 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}`

**Comment by nickvergessen** [comment]
Duplicate #104
