### ISSUE TITLE
settings-Site: internal server error

### ISSUE THREAD

**Issue by jetit** [nextcloud/external#104]
### Steps to reproduce
1. activate External-App
2. go to settings-Site
3. get internal server error

When I deactivate the App, the Settings-Site haven’t any Problems.

### Expected behaviour
Functional settings-Site.

### Actual behaviour
if the External-App is activated in my nextcloud then I can't go to the settings-Site. Every time I become an internal server error.

### Server configuration

**Operating system**:
cantOS 7.5.1804

**Web server:**
Apache 2.4.6

**Database:**
mysql 5.5.56

**PHP version:**
7.0.27

**Nextcloud version:** (see Nextcloud admin page)
13.0.2.1

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.zip

**List of activated apps:**
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - audioplayer: 2.3.0
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - drawio: 0.8.9
  - external: 3.0.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxpod: 2.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.6
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - radio: 0.6.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - calendar
  - encryption
  - music
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "5.45.99.89",
            "v22016083749236526.luckysrv.de",
            "nextcloud.jetit.de",
            "ninaundthomas.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "theme": "",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/nextcloud.jetit.de"
    }
}

### Client configuration
**Browser:**
All Browsers
**Operating system:**
All OS

#### Nextcloud log (data/owncloud.log)
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":3,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: url at \/var\/www\/html\/nextcloud\/apps\/external\/lib\/Settings\/Personal.php#58","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":3,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: redirect at \/var\/www\/html\/nextcloud\/apps\/external\/lib\/Settings\/Personal.php#59","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":3,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: id at \/var\/www\/html\/nextcloud\/apps\/external\/lib\/Settings\/Personal.php#60","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":3,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"index",
"method":"GET","url":"\/index.php\/settings\/user","message":
"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":
\"Parameter \\\"id\\\" for route \\\"external.site.showPage\\\" 
must match \\\"[^\\\/]++\\\" (\\\"\\\" given) 
to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): 
Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'external.site.s...', 1, Array, Array)\\n
#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external.site.s...', Array, 1)\\n
#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('external.site.s...', Array, false)\\n
#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\CachingRouter->generate('external.site.s...', Array)\\n
#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/external\\\/lib\\\/Settings\\\/Personal.php(60): OC\\\\URLGenerator->linkToRoute('external.site.s...', Array)\\n
#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(115): OCA\\\\External\\\\Settings\\\\Personal->getForm()\\n
#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(67): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSettings(Array)\\n
#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n
#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n
#9 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n
#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n
#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n
#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n
#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n
#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n
#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n
#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n
#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WxeihB81fx2gKu95Q4B8wwAAAAI","level":0,"time":"2018-06-06T08:59:48+00:00","remoteAddr":"194.39.189.11","user":"jet","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/html\/nextcloud\/core\/css\/header.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

#### Browser log
Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, senden Sie bitte die nachfolgenden technischen Einzelheiten an Ihren Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 194.39.189.11
Anfragekennung: WxfLPvRxnNxk9gP1I@ONKAAAABk

**Comment by jetit** [comment]
Hi,

if the External-App is activated in my nextcloud then I can't go to the settings-Site. Every time I become an internal server error. 
When I deactivate the App, the Settings-Site haven’t any Problems.

Do you have any Ideas?

Thanks!
Thomas

**Comment by Pisoko** [comment]
Same to me!

**Comment by oskiebe** [comment]
+1

**Comment by mcwimh** [comment]
Got the same strange behavior, except i noticed that only my personal settings are not reachable.
If i type https://domain.com/settings/admin i can access all other settings.
With some changes in the settings of the external sites ik can get to the personal settings, however i can't change any of the personal settings, the privacy settings disappeared.
Attached a good and bad example (good one is on a rip/debian, the bad one is on Ubuntu)
![good](https://user-images.githubusercontent.com/3418606/41527749-63287712-72e8-11e8-8e02-e1db07dc52c8.png)
![wrong](https://user-images.githubusercontent.com/3418606/41527750-63419d64-72e8-11e8-906f-8b8304a702cf.png)

**Comment by dartcafe** [comment]
This error occurs, if a site has been setup to appear in the user quota. If I change the stettings, so that after the change no external site is setup to appear there any more, the error rises up, if I want to access the personal settings. 

Configuring one of the sites to the appear in the user quote, the access is possible again.

**Comment by jetit** [comment]
Thanks! The workaround works fine for me.

**Comment by nickvergessen** [comment]
Sorry for the troubles, it works fine on Nextcloud 14, but on 13 we cache the entries in the database and that's what's the problem. When there ever was a quota link for now there always has to be one.

I will try to think of a way that can remove it, without too much hassle.
