### ISSUE TITLE
Edit or delete site doesn't seem to work

### ISSUE THREAD

**Issue by PhieF** [nextcloud/external#105]
### Steps to reproduce
1. add site
2. edit (bug)
3. delete (bug)

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** NC 13.0.3

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) NC 13.0.3

**Where did you install Nextcloud from:** ? website

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:33+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Repair::step: Repair step: Add log rotate job","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:33+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Repair::step: Repair step: Clear frontend caches","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:33+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Repair::info: Repair info: Image cache cleared","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:34+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:35+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:35+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:37+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:37+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.3.2"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:37+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.3.2"}
{"reqId":"77PO6snn49PLokHktPQZ","level":1,"time":"2018-06-07T23:19:37+00:00","remoteAddr":"192.168.1.13","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QgPIi0Unt0P7Gh7UWqZrDiAnZCoVsf1RJCl2zO7UKC8%3D%3ADXGw2AZL2S2uX3jmKNcsR2JhC3l%2FxJcwUGsbqpvjQFY%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.3.2"}

**Comment by rollanders** [comment]
I can verify this behaviour.

**Comment by nickvergessen** [comment]
The log messages are all unrelated.

ALso I just checked this again and the latest version works just fine.
If you get problems again, please be more specific and fill out the questions of the issue template, especially the browsers JS console output is important in this case.
