### ISSUE TITLE
Make it possible to use "mailto:test@test.com"

### ISSUE THREAD

**Issue by Pisoko** [nextcloud/external#107]
Dear Developers,
thanks for this great app!

It would be so nice if the app would accept other formats than "http(s)".
For instance the use of mailto to implement an external site with mailto:test@test.com in nextcloud that opens you outlook with the filled in mail address.

Cheers
Pisoko

**Comment by nickvergessen** [comment]
Sorry, this does not work with the current way to app is implemented.
