### ISSUE TITLE
Redirect info not available via api

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/external#109]
On settings there is "redirect: [ ] this site does not allow embedding".
But via https://$server/ocs/v2.php/apps/external/api/v1, I do not get this info:
```
<element>
	<icon>https://$server/index.php/apps/external/icons/external.svg</icon>
	<type>link</type>
	<id>4</id>
	<name>NC Mail</name>
	<url>https://$server/index.php/apps/mail/#accounts/-1/folders/Y</url>
</element>
```

Can you please provide this info? 
Then I can either show the link within a webview in our app or force open up the link in an external browser.

**Comment by nickvergessen** [comment]
Hmm makes sense, not sure why I killed it initially

**Comment by tobiasKaminsky** [comment]
I am not good at php, but it seems that it is just missing: 
https://github.com/nextcloud/external/pull/43 and https://github.com/nextcloud/external/blob/master/lib/SitesManager.php#L120

**Comment by nickvergessen** [comment]
No, the error is https://github.com/nextcloud/external/blob/master/lib/Controller/APIController.php#L89 where we kill it.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/external/commit/00af97b0aa2ff831ecf4deb42c08a8a035579430

**Comment by tobiasKaminsky** [comment]
Thanks, I added this to android client, with a false as default for older app versions.
