### ISSUE TITLE
Live update the header menus when managing sites

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/external#11]
1. Add on create
2. Modify on update
3. Remove on delete

@juliushaertl interested?

**Comment by juliushaertl** [comment]
@nickvergessen A quick fix for the app menu is in #19, updating the settings menu as well will require some more changes. 

Are external links with quota setting displayed somewhere in the webapp?

**Comment by nickvergessen** [comment]
> Are external links with quota setting displayed somewhere in the webapp?

No,

But I guess main navigation is most important, since it's displayed.
