### ISSUE TITLE
Links on login pages

### ISSUE THREAD

**Issue by michag86** [nextcloud/external#111]
Add the possebility to add links to the login page, as described by @juliushaertl in this issue: nextcloud/server#10235

The use case
The theming app supports to add a link to legal notice and privacy policy. But we want to add a contact link (mailto with defined subject).

cc @MorrisJobke

**Comment by bor8** [comment]
This would also be wonderful for shares that external users can see.

**Comment by bor8** [comment]
Thank you. I'll take care of it. But do you also see the links on the page where externals can download files? And if yes, can you provide a (further) screenshot?
