### ISSUE TITLE
Add relative url for external sites

### ISSUE THREAD

**Issue by DeAlexPesh** [nextcloud/external#120]
Hi?
My Nextcloud have two domain.
Can I add external sites with relative url as: /cloud/link/site.html ?

**Comment by nickvergessen** [comment]
No, as the external sites are also handed out to the mobile and desktop client

**Comment by DeAlexPesh** [comment]
...apps/external/lib/SitesManager.php
**for:**
_public function addSite(...
public function updateSite(..._
**change this code:**
```
...
if ($url[0] === '/' && filter_var('http:/'.$url, FILTER_VALIDATE_URL) !== false) {
  $device = self::DEVICE_BROWSER;
} else {
  if (filter_var($url, FILTER_VALIDATE_URL) === false ||
    strpos($url, 'http://') === strpos($url, 'https://')) {
    throw new InvalidURLException();
  }
}
...
```
but it only for browser. it's bad ( Maybe posible made autoconcatination request domain to begin this url on request from no browser?
