### ISSUE TITLE
Entries placed below settings dropdown

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/external#122]
When there are more than one external sites positioned in the settings dropdown, the lowest menu entries such as `Log out` are placed below the menu field.

**PHP version:** 7.2
**Nextcloud version:** 14.0.1

![screenshot_logout_belowfield](https://user-images.githubusercontent.com/36013390/46659620-9094f380-cbb5-11e8-9d33-9c773f3004a2.png)

**Comment by nickvergessen** [comment]
@skjnldsv is the menu fixed height?

**Comment by skjnldsv** [comment]
> @skjnldsv is the menu fixed height?

Apparently to 280 yes :)
there is no `overflow-y: auto;`

**Comment by daniel-wtd** [comment]
Same reported here:

- https://github.com/nextcloud/server/issues/11843
- https://github.com/nextcloud/server/issues/11791

**Comment by nickvergessen** [comment]
Closing as duplicate of https://github.com/nextcloud/server/issues/11791
