### ISSUE TITLE
SFTP external needs to show host key for verification purposes

### ISSUE THREAD

**Issue by fletch31337** [nextcloud/external#124]
### Steps to reproduce
1. Add a host via SFTP
2. Try and access it.
3. There is no point where the host key is shown for verification - MAJOR security issue.

### Expected behaviour
When an administrator or user (if user external access is allowed) adds a host via SFTP, the host key
should be displayed for verification before allowing connection.

### Actual behaviour
The user/admin is allowed to connect directly to the host.  Either the SSH host key given is simply accepted or connection goes ahead regardless and the host key is ignored.

**Operating system**:
Multiple

**Web server:**
Apache

**Nextcloud version:** (see Nextcloud admin page)
13

**Where did you install Nextcloud from:**
Snap

**List of activated apps:**
External

### Client configuration
**Browser:**
Firefox (Latest)

**Operating system:**
Windows and Linux

**Comment by nickvergessen** [comment]
This is not the app you are looking for.
The issue you want to report is the files_external app, so report your issue here please:
https://github.com/nextcloud/server/issues/new
