### ISSUE TITLE
(NC 14.0.3 updated) External Sites APP won't work

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/external#125]
### Steps to reproduce
1. Activate or reinstall External Sites
2. Open in Settings -> External Sites
3. Error (Contact Sysadmin)

### Expected behaviour
Should work as before or better.

### Actual behaviour
Error Message

### Server configuration

**Operating system**: Ubuntu 16.0.4.10 4.4.0-138.164-generic 4.4.15

**Web server:** Apache/2.4.18

**Database:** MYSQL 5.7.24-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 14.0.3

**Where did you install Nextcloud from:** Command line Updater 12.0.3 -> 13.0.4 -> 14.0.3

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - direct_menu
  - documents
  - encryption
  - external
  - files_antivirus
  - mail
  - news
  - notes
  - ownnote
  - ownpad
  - richdocuments
  - spreed
  - theming
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx",
            "xxxxx",
            "xxxxx",
            "xxxxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "appstore.experimental.enabled": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 1,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "theme": "owntheme",
        "updater.release.channel": "production",
        "integrity.check.disabled": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritecondaddr": "^127\\.0\\.0\\.1$",
        "overwrite.cli.url": "https://xxxxxxxxxx",
        "mail_template_class": "\\OC\\Mail\\EMailTemplate_neu"
    }
}

### Client configuration
**Browser:** Happens on newest Chrome, Firefox, Edge...

**Operating system:** WIN 10

#### Error
```
RuntimeException: image not found: image:actions/checkmark-color.svg webroot: serverroot:/var/www/nextcloud
```

**Comment by nickvergessen** [comment]
The icon `checkmark-color` is not used by this app.
Can you check your log files for more errors and which app is using this icon?

**Comment by nickvergessen** [comment]
what is your apps_path config now?

**Comment by ExaconAT** [comment]
No apps_path in my config now

**Comment by ExaconAT** [comment]
I've overwritten all files again with a fresh installation now the Icons won't even appear anymore in the Header Menu

![grafik](https://user-images.githubusercontent.com/33482537/48538288-55709900-e8b4-11e8-834f-fb5b36048d62.png)
