### ISSUE TITLE
Request: Make LAN internal sites available to non LAN users

### ISSUE THREAD

**Issue by PeeBeerBeach** [nextcloud/external#128]
I have a website running only on internal LAN. It would be very beneficial if I could embedd this site into Nextcloud and make it available to users that login from the internet but have no access to the LAN.

The reason for this request is that the internal website has no security and login/password prompt but gives access to integral parts of my local devices. 
Also it would of course be nice to have everything available in 1 place: the Nextcloud GUI without having to install VPN client or else.

**Comment by nickvergessen** [comment]
Sorry, this was requested before already, but we are not going to integrate a Proxy into a small nextcloud app
