### ISSUE TITLE
Group external sites in apps menu

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/external#132]
When using several external sites the main menu gets crowded:
![bildschirmfoto_2019-02-22_19-00-38](https://user-images.githubusercontent.com/29312856/53261406-357f1b80-36d4-11e9-84b5-20a8385c6762.png)

A great enhancement would be the possibility to group sites in a defined drop-down selection alike the 3-dot "more" option in the main menu.

![bildschirmfoto_2019-02-22_19-06-53](https://user-images.githubusercontent.com/29312856/53261734-1339cd80-36d5-11e9-94c1-7432773687e8.png)

For example, we are using several whiteboard instances for different user groups. If you belong to e.g. 5 groups, you will get 5 different whiteboards displayed in the main menu.
A good solution would be groups that appear as drop-down menus and can be created by admins with configurable icon and description, to which you can then add external sites.

**Comment by nickvergessen** [comment]
I'm closing this as it is currently out of scope for this app. The server does not allow an app to define such a grouping.
