### ISSUE TITLE
Access from not assigned groups by trying other numbers in URL

### ISSUE THREAD

**Issue by job963** [nextcloud/external#136]
### Steps to reproduce
1. Create two external sites and assign to each a different user group
2. Login with an user who is assigned to only one of these two user groups
3. This user can see only the allowed external site - correct
4. Click on that link (url = https://www.domain.tld/index.php/apps/external/1)
5. Edit the URL in the address line manually to https://www.domain.tld/index.php/apps/external/2 and press enter

### Expected behaviour
The second external site (which is assigned to another group should be not accessible and manual entering the URL should return 404

### Actual behaviour
The second (not allowed) URL will be opened and displayed

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14 and 15

### Client configuration
**Browser:**
* Chrome
* Firefox
* Brave
* Vivaldi

**Comment by nickvergessen** [comment]
The main issue is, that if you follow those links from the mobile clients or the desktop client the request is not authenticated, so it would currently break the designed use-case.
@tobiasKaminsky could this be changed?

**Comment by tobiasKaminsky** [comment]
We can change this. 
We do get the link infos via /ocs/v2.php/apps/external/api/v1 and this is already authenticated.
Maybe an idea is to not use guessable ids, but just a random 10 digit long "id"?
The id is not used in android.

**Comment by job963** [comment]
A large random number would be fine or you use a random character string like on sharing a file.

**Comment by morbificagent** [comment]
I have a big problem with this too... 
We  are trying to publish an external site only sometimes to specific users wich are part of that access-group for some days.
We want to send them the Link to it in a mail like

https://www.domain.tld/index.php/apps/external/2

So the user hasnt to search for this site (you know... users... ;-) )

After that we want to kick them out of that group so they cant access this external site anymore.

But as said before the Link/icon wents away after kicking them out of the group but they can use the given link even if they have no rights to this external site :-(

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/external/pull/244
