### ISSUE TITLE
Settings-Menu overloaded with more than 3 external sites 

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/external#140]
You can reproduce this bug with the official Nextcloud 16 demo.
Install the external sites App, add more than 3 external sites, put them into the settings menu.

I tested this with firefox 66.0.3

![menubug](https://user-images.githubusercontent.com/5323995/57520645-745d5e80-731e-11e9-8fc8-47bd2fda94fc.png)

**Comment by jolly-jump** [comment]
Have the same: see here: https://help.nextcloud.com/t/personal-menu-overlay-too-small/53460

**Comment by jolly-jump** [comment]
thanks for trying to get this fixed!
