### ISSUE TITLE
White images on android navigation drawer

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/external#16]
I get the images via API and use them on the navigation drawer in our android app.
The background color of this navigation drawer is white, which leads to not "showing" the external icons as they are then white on white.
Only settings.svg is working as it is black by default.

This is also the same if you look into the web UI and open the upper right menu.

I will need some black ones for proper displaying them.

**Comment by ColdSphinX** [comment]
you could just convert the icons on the server: `convert $image -negate -alpha copy invert-$image`

**Comment by tobiasKaminsky** [comment]
This is indeed possible for experienced admins, but this should be done automatically on server side as it is done with the font changing to black if the background color is too light.

**Comment by nickvergessen** [comment]
we shall have a look at this, once people upload the icons through an UI and we have to serve them from the app anyway #5
