### ISSUE TITLE
improve reliability and GUI administration

### ISSUE THREAD

**Issue by TP75** [nextcloud/external#164]
### Steps to reproduce
Establish several items i.e. **a set of mixed website entries** to the 'External sites' app sequentially and **with different locales selected** to the admin account in use. Arbitrarily re-order these items by help of the ['App order' app](https://github.com/juliushaertl/apporder/) with different locales selected. 

Arbitrarily select and deselect the administrative views of both apps several times each and make changes to the resp. app settings inside each of their views. 

### Expected behaviour

1. The list of 'External sites' shall be limited to the number of items of the intendend GUI input from the administrator.
2. The combination of the 'External sites' app with the 'App order' app should provide a stable set of data. 
1. Any combination of locales and languages shall establish a reasonable data set for external sites in the database without loosing flexibility. 

### Actual behaviour

While establishing the a.m. mixed items by the 'External sites' app view several times some or even more **superfluous items** were observed. These entries appeared automatically and were redundantly listed in the view i.e. became added automatically to the bottom of the websites list. However, the viewed superfluous entries apparently vanished after closing the 'External sites' app view and could not be found in the GUI administration later.

No errors were found in the 'Logging' GUI. Only some days later the apparent b.m. issue of "the 'app list' of doom" was observed by coincidence and from several different NC desktop clients connected to this NC server. Presumably, the a.m. **superfluous entries** only vanished from the GUI admin view but as data entries **unfortunately remained in great numbers** in the database.

## Server configuration detail

For details on the server config and the **more general issue** refer to [nextcloud/server - improve GUI administration for multi-language collaborative efforts # 17631](https://github.com/nextcloud/server/issues/17631)

## Client configuration

For details on the client config and the **relevant NC desktop screenshots** refer to  [nextcloud/desktop - avoid "the 'app list' of doom" # 1545](https://github.com/nextcloud/desktop/issues/1545)

**Comment by nickvergessen** [comment]
Reordering of external sites is still on the todo: #70 
I'm not sure what the app order app does, but I can imagine it doesnt work too good with this app.

**Comment by nickvergessen** [comment]
Okay, I quickly installed it and it worked fine. the only problem is, that the admin can of course only manage sites in apporder which they see in the navigation. Becuase that is where the apporder app gets it's data from.

cc @juliushaertl

**Comment by TP75** [comment]
@nickvergessen Thank you.

@juliushaertl Please be aware the main issue is not the question of re-ordering but the more major issue of *automatically produced superfluous entries which have unwanted side effects in reducing the usabiliy of the desktop client* unfortunately.

**Comment by juliushaertl** [comment]
> The combination of the 'External sites' app with the 'App order' app should provide a stable set of data.

apporder is more a hacky approach and only supports reordering in the web UI. Once we have the reordering done in the server with https://github.com/nextcloud/server/issues/4917 we can make sure that the order also applies to the desktop client.

> Automatically produced superfluous entries which have unwanted side effects in reducing the usabiliy of the desktop client unfortunately.

I cannot reproduce that. The desktop client should just display the list from the following api endpoint:

curl 'https://admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/core/navigation/apps?format=json' | jq .

Can you check if the output is stable? In that case it is an issue of the desktop client appending new items instead of replacing the list.

**Comment by TP75** [comment]
Update: A Version 2.5.1git desktop client on Linux shows the expected behaviour while connecting the same NC server as above.

_Originally posted by @TP75 in https://github.com/nextcloud/desktop/issues/1545#issuecomment-544885114_

Maybe not truly related to 'External sites' as presumed before?

Maybe the issue is limited to an unstable Version 2.6.1RC1 desktop client only?

**Comment by TP75** [comment]
@juliushaertl 

#### A)

> I cannot reproduce that. The desktop client should just display the list from the following api endpoint:

please ref nextcloud/desktop#1545

Maybe the issue is limited to an unstable Version 2.6.1RC1 desktop client only?

#### B)

> curl 'https://admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/core/navigation/apps?format=json' | jq .

Unfortunately, the URL provided by you is producing a [security warning](https://support.mozilla.org/kb/what-does-your-connection-is-not-secure-mean).

- - -  
Der Inhaber von nextcloud.local.dev.bitgrid.net hat die Website nicht richtig konfiguriert. Firefox hat keine Verbindung mit dieser Website aufgebaut, um Ihre Informationen vor Diebstahl zu schützen.

nextcloud.local.dev.bitgrid.net verwendet ein ungültiges Sicherheitszertifikat. Das Zertifikat gilt nur für folgende Namen: local.dev.bitgrid.net, local13.dev.bitgrid.net Fehlercode: 
  ` SSL_ERROR_BAD_CERT_DOMAIN_ `

---

**Comment by TP75** [comment]
The unfortunate but not unexpected result was:

```
$ curl 'https://admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/core/navigation/apps?format=json' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'nextcloud.local.dev.bitgrid.net'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
NB: [MacPorts](https://www.macports.org/) environment on macOS 10.14.6 Mojave with [curl - Tool for transferring files with URL syntax](https://ports.macports.org/port/curl/summary) and [jq - A lightweight and flexible command-line JSON processor](https://ports.macports.org/port/jq/summary)

-   curl @7.66.0_0+ssl (active)
-   curl-ca-bundle @7.66.0_1 (active)
-   jq @1.6_1 (active)
-   oniguruma5 @5.9.6_p1_0 (active)

**Comment by juliushaertl** [comment]
Sorry, i should have mentioned that you need to replace the url/account credentials of my development instance with yours ;)

**Comment by juliushaertl** [comment]
> Maybe the issue is limited to an unstable Version 2.6.1RC1 desktop client only?

Most likely, yes.

**Comment by TP75** [comment]
> Sorry, i should have mentioned that you need to replace the url/account credentials of my development instance with yours ;)

Tja, so etwas nennt man dann im Denglischen Jargon wohl "[tazites Wissen](https://de.wikipedia.org/wiki/Implizites_Wissen)" und könnte man (wie ja jetzt auch freundlicher Weise geschehen) mal erläutern. Den fraglichen Vorspann in der Adresse habe ich ansonsten vielleicht auch einfach mal in der Schnelle überlesen und nicht vorher nachgedacht. :wink:

Errare humanem est.

From you last advice I can deduce `admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/core/navigation` should change the preface `admin:admin@nextcloud.local.dev.bitgrid.net` with my credentials. I would give it a try and please stay tuned...

Ergo cogito sum.

**Comment by TP75** [comment]
### The motto

Fiat lux.

### The docs

The two sources:

[NC 16 OCS APIs overview](https://docs.nextcloud.com/server/16/developer_manual/client_apis/OCS/ocs-api-overview.html#testing-requests-with-curl) - "This document provides a quick overview of the OCS API endpoints supported in Nextcloud."

and


> curl 'https://admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/core/navigation/apps?format=json' | jq .

in combination make things happen.

### The tools

see above

### The CLI activity & output

``` 

$ curl 'https://admin:redacted@cloud.redacted.tld/ocs/v2.php/core/navigation/apps?format=json' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1838  100  1838    0     0   6426      0 --:--:-- --:--:-- --:--:--  6426
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": [
      {
        "id": "files",
        "order": "0",
        "href": "/index.php/apps/files/",
        "icon": "/apps/files/img/app.svg",
        "type": "link",
        "name": "Files",
        "active": false,
        "classes": ""
      },
      {
        "id": "activity",
        "order": "1",
        "href": "/index.php/apps/activity/",
        "icon": "/apps/activity/img/activity.svg",
        "type": "link",
        "name": "Activity",
        "active": false,
        "classes": ""
      },
      {
        "id": "gallery",
        "order": 2,
        "href": "/index.php/apps/gallery/",
        "icon": "/apps/gallery/img/app.svg",
        "name": "Gallery",
        "active": false,
        "classes": "",
        "type": "link"
      },
      {
        "id": "contacts",
        "order": 4,
        "href": "/index.php/apps/contacts/",
        "icon": "/apps/contacts/img/app.svg",
        "name": "Contacts",
        "active": false,
        "classes": "",
        "type": "link"
      },
      {
        "id": "calendar",
        "order": 5,
        "href": "/index.php/apps/calendar/",
        "icon": "/apps/calendar/img/calendar.svg",
        "name": "Calendar",
        "active": false,
        "classes": "",
        "type": "link"
      },
      {
        "id": "notes",
        "order": 10,
        "href": "/index.php/apps/notes/",
        "icon": "/apps/notes/img/notes.svg",
        "name": "Notes",
        "active": false,
        "classes": "",
        "type": "link"
      },
      {
        "id": "announcementcenter",
        "order": "10",
        "href": "/index.php/apps/announcementcenter/",
        "icon": "/apps/announcementcenter/img/announcementcenter.svg",
        "type": "link",
        "name": "Announcements",
        "active": false,
        "classes": ""
      },
      {
        "id": "polls",
        "order": 77,
        "href": "/index.php/apps/polls/",
        "icon": "/apps/polls/img/app.svg",
        "name": "Polls",
        "active": false,
        "classes": "",
        "type": "link"
      },
      {
        "id": "external_index3",
        "order": 83,
        "href": "https://docs.nextcloud.com/server/16/user_manual/webinterface.html",
        "icon": "/index.php/apps/external/icons/external.svg",
        "type": "link",
        "name": "Manual (EN)",
        "active": false,
        "classes": ""
      },
      {
        "id": "tasks",
        "order": 100,
        "href": "/index.php/apps/tasks/",
        "icon": "/apps/tasks/img/tasks.svg",
        "name": "Tasks",
        "active": false,
        "classes": "",
        "type": "link"
      }
    ]
  }
}
``` 

### The conclucion

The issue is limited to an unstable Version 2.6.1RC1 desktop client if I understand the above correctly.

q.e.d.

**Comment by TP75** [comment]
See you at nextcloud/desktop#1545 again...
