### ISSUE TITLE
make true redicts possible

### ISSUE THREAD

**Issue by TP75** [nextcloud/external#165]
### Steps to reproduce

Choose a NC 16 GUI from a browser convenient to you and your OS e.g., the current [Mozilla Firefox ESR](https://www.mozilla.org/en-US/firefox/enterprise/) for macOS.

1. Login to NC GUI as an admin.
1. Establish website item to the 'External sites' app and make the resp. 'Redirect' checkbox selected. 
1. Try to access this website link directly from the app list in the top bar.

### Expected behaviour

The link should be opened from the selected tab in a new window or a new tab but not in the same tab view. The selected tab view shall remain active and not be closed nor removed.

ref to [External Sites: OCS API - Response -Explanation](https://github.com/nextcloud/external#explanation)

> redirect | int | Whether the link should be opened inline or in a new window

### Actual behaviour

The link is opened inline and not embedded but replacing all NC content in the current tab view of the browser.

## Server configuration detail

For details on the server config ref to nextcloud/server#17631

## Client configuration

For details on the client config refer to nextcloud/desktop#1545

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/external/issues/79
