### ISSUE TITLE
Use font awesome icons instead of user created svgs

### ISSUE THREAD

**Issue by lil5** [nextcloud/external#166]
### Feature Request

1. at external site settings
2. click on 'Select an icon'
3. font awesome is in selection
4. text input is then shown
5. type in  'fas fa-cloud-rain'

**Comment by nickvergessen** [comment]
This is not possible, because the solution works cross plattform and the desktop and mobile clients dont ship font-awesome.
But I guess there is a place somewhere, where you can download the font-awesome things as images.
