### ISSUE TITLE
Quota link hidden since 3.4.1

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/external#167]
### Steps to reproduce
1. configure an external site with position "User quota"
2. go to the Files page

### Expected behaviour
Quota link shows up under the quota bar

![image](https://user-images.githubusercontent.com/1804221/68967154-e8058a00-07df-11ea-8c63-f93bcba174d6.png)
_screenshot from NC 16.0.6 with external sites app 3.3.1_

### Actual behaviour
Quota link is hidden within the quota bar (clicking the quota bar opens the link).
![image](https://user-images.githubusercontent.com/1804221/68967389-6e21d080-07e0-11ea-9b3f-04d0d7726c79.png)

_screenshot from NC 17.0.1 with external sites app 3.4.1_

**Comment by nickvergessen** [comment]
This is broken due to the content security policy.
I will have a look.
