### ISSUE TITLE
Multiple quota links is broken again

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/external#173]
### Steps to reproduce
1. Set up 2 links with quota

### Expected behaviour
See both buttons in the UI

### Actual behaviour
Only 1 button is shown

**Comment by nickvergessen** [comment]
So actually this was reverted when we changed it to be clickable on the quota bar in the files app in https://github.com/nextcloud/external/pull/40

**Comment by provokateurin** [comment]
I assume this can be/has to be fixed with https://github.com/nextcloud/external/issues/457?
