### ISSUE TITLE
Use more Icons for the external page

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/external#174]
Hi,

now there are only two icons available to select for external page icon
- external
- settings

In addition that both are the same, are you interested in add more icons? I'm thinking of two options:
1. reuse the existing icons from NC (the one from settings section, ...)
2. add new icons to the external/img

for option 2 I can make them, but I think option 1 would be better.

**Comment by nickvergessen** [comment]
There is a section where people can upload their own icons.
We are not going to add more default icons.
