### ISSUE TITLE
external icon download button as template for user specific icons

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/external#175]
The external app offers only one icon the globe icon called external.svg and external-dark.svg 

If you would like to make your own icon fit the general NC layout, it would be very helpfull to offer an template download button with download this two files the user can edit them and the new user designed icons fit's the size/color/... layout of the template file.

I for example search for the file on github, download the git repository and made from the external files the company based file for external page.

**Comment by nickvergessen** [comment]
You should be able to download them just fine by right-click on them in the icon management just below the external sites
