### ISSUE TITLE
Site as sidebar

### ISSUE THREAD

**Issue by skug67** [nextcloud/external#178]
Great app, thanks for creating/maintaining it.  I was wondering if there might be a way to provide an option where instead of taking over the entire Nextcloud frame the external site could slide-in/slide-out from the side (covering, or even better resizing, only a portion of the main frame).  Kind of like the JavaScript XMPP Chat app (ojsxc, https://apps.nextcloud.com/apps/ojsxc).

Thanks again,

Seth Green

**Comment by nickvergessen** [comment]
This is out of scope atm and would add a lot of complexity.
