### ISSUE TITLE
Automatic login to external site?

### ISSUE THREAD

**Issue by luvis** [nextcloud/external#181]
This is a question from a non coder so I don't know what's possible but I was thinking that it would be amazing if the external sites plugin could save login information to an external site. Specifically I'm currently using roundcube as an external site which works really well but it would really make it feel seemless if it would auto-log in from nextcloud. I'm thinking that there are password managers with extensions that autofill password forms and log in, would it be possible to use a similar approach and "pre"- log in in the background as soon as one has logged in to NC?

**Comment by floogy** [comment]
You can get the username of the logged-in Nextcloud user from within the iframe.

Assuming jQuery is enabled in the frame::

`var nc_user = window.parent.$('head').attr('data-user');`

Of course, this is insufficient for security as someone could find your JavaScript and easily fake the frame.

Did you ever find a workaround for this?

**Comment by nickvergessen** [comment]
This is really not possible at the moment. And also I'm not sure it should be. I really dislike the idea of passing on credentials to other sites (could be highjaked after all).

There are still things trying to move this forward, e.g. #146 so I'm closing this.
