### ISSUE TITLE
External sites with login cannot store cookies?

### ISSUE THREAD

**Issue by nooblag** [nextcloud/external#184]
#Steps to reproduce
1. Add https://webmail.gandi.net/SOGo/ or https://subdomain.rocket.chat/ as an external site, no redirect.
2. Open external site from menu, attempt to login.

### Expected behaviour
Not sure.

### Actual behaviour
On submitting form to login for first link site shows error message "You cannot login because your browser's cookies are disabled. Please enable cookies in your browser's settings and try again."

For other sites that require a login, such as https://subdomain.rocket.chat/ no error is shown but form does not display.

Is this because of cookies? Is there a way to allow embedded site to write cookies to a path on Nextcloud server so these sites can be displayed inside Nextcloud?

### Server configuration

**Operating system:** Ubuntu 18.04.4 LTS

**Web server:** nginx 1.16.1

**Database:** psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

**PHP version:** PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )

**Nextcloud version:** 18.0.2

**Where did you install Nextcloud from:**
nextcloud.com

**Comment by nickvergessen** [comment]
No, this is because the sites do not allow to be iframed. Make them redirect instead and it should work

**Comment by nooblag** [comment]
I'm not so sure. Testing this line in a blank HTML file worked fine:
`<iframe id="ifm" src="https://webmail.gandi.net/SOGo/" allowfullscreen></iframe>`
Are you sure there is no issue with Nextcloud?
