### ISSUE TITLE
Feature Request: Ability to reorder sites

### ISSUE THREAD

**Issue by Luticus** [nextcloud/external#190]
Any chance we can get the ability to reorder the sites in the settings menu?  If I want to reorder them currently I'd have to delete all my sites and add them back in the correct order.  I can do that, but it would be a bit more polished if I could simply drag them into the correct order.

**Comment by Dubidubiduu** [comment]
@Luticus Actually you can reorder the sites with the "app order -app". Limitation: The external sites doesn't have a group limitation.

**Comment by nickvergessen** [comment]
Duplixate of #70
