### ISSUE TITLE
Is there a limit on the admin UI for number of external sites?

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/external#193]
### Steps to reproduce
1. Add a 4th site
2. ...
3. ...

### Expected behaviour

A 4th external site should appear

### Actual behaviour

Site id 1 is replaced with the new one, seems to be a hard-coded limit of 3 sites

### Server configuration

**Operating system**: 

Ubuntu 18

**Web server:** 

Nginx

**Database:** 

MariaDB 10.4

**PHP version:** 

7.2

**Nextcloud version:** (see Nextcloud admin page) 

18.04

**Where did you install Nextcloud from:** 

latest.zip

I can add a 4th site by manually appending the json array and adding them via occ, but the web ui doesn't produce 4, even if 4 are displayed.  Verified by checking occ get output which shows the new site replacing one of the existing ones, and only 3 total.

**Comment by nickvergessen** [comment]
No, works fine here and we never had an artificial limit.

**Comment by RNCTX** [comment]
No, you're wrong, it does not work fine.

I suspect this is another example of Nextcloud's universally poor cache implementation.  *A LOT* of weird Nextcloud bugs can be explained by simply turning the cache off, I'd wager...

https://youtu.be/L9YMXsOvY18
