### ISSUE TITLE
No, you're wrong, it does not work fine

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/external#195]
#193 

But since you closed that report without any reasoning whatsoever here's another one to cost you another few clicks.

I suspect this is another example of Nextcloud's universally poor cache implementation. A LOT of weird Nextcloud bugs can be explained by simply turning the cache off, I'd wager...

https://youtu.be/L9YMXsOvY18

**Comment by nickvergessen** [comment]
So the error is you setting the value manually via occ without changing the related value `max_site` in the same step. So don't fiddle manually in data you don't fully grasp, and all will be eventually fine/better, just use the web UI to define your links instead.


![Peek 2020-05-15 08-18](https://user-images.githubusercontent.com/213943/82018111-de70b800-9684-11ea-87ac-2db913898bb2.gif)
