### ISSUE TITLE
Can ‘external sites’ get informations from Nextcloud?

### ISSUE THREAD

**Issue by KoljaL** [nextcloud/external#201]
Is there a way with the app “external sites” that the included page gets information from Nextcloud?
The name and groups of the registered user would be very practical.

If not, is there a way for the included page to know that it is accessed through the Nextcloud app?
My first idea with `$_SERVER["HTTP_REFERER"]` & co does not work.

**Comment by nickvergessen** [comment]
Available placeholders for the URL are:
{email}, {uid} and {displayname}

No further information is planed to be forwarded. If you want to authenticate the user on your next site, you should do this properly with e.g. OAuth which we provide.
