### ISSUE TITLE
Security Problem

### ISSUE THREAD

**Issue by MichaelBarth** [nextcloud/external#202]
Hello,
I use the uid to show the user personal informations (eg. personal time-schedule). By just changing the uid in the url-parameter of the iframe it is possible to see the personal Informations of someone else. That should not be!
Is there a possibility to prevent this url manipulation? Sending a JWT could be a solution! That means, sending  an additional  password encoded hash of the url parameters.

Greatings
Michael

**Comment by nickvergessen** [comment]
See #146 

And well it's a security problem on your page if it shows data based on URL without checking authentication.
