### ISSUE TITLE
Feature: embed external site inside of files view (position "root folder")

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/external#207]
I'd really like to have an additional position setting called "Root folder" which creates a new folder inside of the users root folder (showing up like a external storage). This folder behaves like a link so exactly the same like all other possible link types (positions).

User story: 

> As a Nextcloud administrator i'd like to embed a public link to a file platform (like Sharepoint) into my Nextcloud instance to give my users the possibility to navigate to the shares inside the files view.

If you like this feature i'd really be looking forward to implement this.

**Comment by gary-kim** [comment]
I believe it would be possible to achieve what you'd like with https://github.com/te-online/files_linkeditor

**Comment by R0Wi** [comment]
> I believe it would be possible to achieve what you'd like with https://github.com/te-online/files_linkeditor

Thanks for the hint, will try that...

**Comment by R0Wi** [comment]
@gary-kim works perfectly, thanks for that :-) App allows to create and edit these link-files at any location inside of Nextcloud and jumps to the URL if the user clicks on that file. Also links can be shared to users and groups like any other file.
