### ISSUE TITLE
can inject NextCloud any variable ?

### ISSUE THREAD

**Issue by virtuoseit** [nextcloud/external#209]
hi,
my question is :
is it possible to insert any variable into the url ?
for an example something like that : https://myurl.url/{NextCloud_CurrentUSER}/?value={Any_NextCloud_Variable}

best regards,

**Comment by nickvergessen** [comment]
As per admin settings:
> The placeholders {email}, {uid} and {displayname} can be used and are filled with the user´s values to customize the links.
