### ISSUE TITLE
Group restriction fail in NC 19

### ISSUE THREAD

**Issue by jolly-jump** [nextcloud/external#212]
### Steps to reproduce
1. update to NC 19
2. as admin: go to settings -> external sites
3. click on any already existing entry or create a new one

### Expected behaviour
It should show what groups the external sites can be restricted to be shown and you should be able to select groups

### Actual behaviour
The Field next to "groups" is not even shown, the server says, after a while "Unable to retrieve the group list" in my case several times as a modal information dialog which has to be x-ed away.

### Server configuration

**Operating system**: Linux 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64

**Web server:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 10.1.44

**PHP version:** 7.2.24-0ubuntu0.18.04.6
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 19.0.2 - 19.0.2.2

**Where did you install Nextcloud from:** 18.0.8

**List of activated apps:** 
- files_retention: 1.8.2
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - forms: 2.0.4
 - impersonate: 1.6.1
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quota_warning: 1.8.0
 - rainloop: 7.0.2
 - richdocuments: 3.7.4
 - riotchat: 0.6.6
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - user_ldap: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - audioplayer
 - bbb
 - deck
 - encryption
 - groupfolders
 - nextcloud_announcements
 - recommendations
 - spreed
 - support
 - user_usage_report

**Nextcloud configuration:**

### Client configuration
**Browser:** Icecat, Chromium

**Operating system:** Linux

#### Nextcloud log
My log basically consists of:
```
{"reqId":"qI3iiwi6Nx6ZRyreoMED","level":3,"time":"2020-09-13T08:59:59+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: instance at /opt/nextcloud/apps/circles/lib/Model/BaseMember.php#388","userAgent":"--","version":"19.0.2.2"}
```
but nothing connected to the "Unable to retrieve the group list"

**Comment by nickvergessen** [comment]
Can you check your browser console (press F12)

**Comment by jolly-jump** [comment]
Sure, thanks for asking: 

```
Object { readyState: 4, getResponseHeader: getResponseHeader(), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(), overrideMimeType: overrideMimeType(), statusCode: statusCode(), abort: abort(), state: state(), always: always(), then: then(), … }
settings.js:95:14
```
and
```
{
  "readyState": 4,
  "responseText": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n",
  "status": 504,
  "statusText": "Gateway Timeout"
}
```

don't know if I should recurse into that object, it does not seem to be more informative, if I do.

**Comment by jolly-jump** [comment]
We are basically only using LDAP groups, so I try to guess, where the timeout comes from and if the timeout lies in  the connection to the LDAP server. 
But everything else in the NC and with ldap_users is working fine.

**Comment by nickvergessen** [comment]
Gateway timeout? That sounds like a generic issue with your server and not related to this app.

**Comment by jolly-jump** [comment]
Well, I wouldn't know.
At least from the empirical perspective: if no one else sees that problem, I might be alone and just unlucky.

I found the corresponding network call:
```
Request URL: https://domain.org/ocs/v2.php/cloud/groups/details
Request method:GET
Remote address: IP-Adress:443
Status code: 504
Version:HTTP/2.0
```
which fails right after basically the same call, with the 
```
:path: /ocs/v2.php/apps/external/api/v1/sites
```
which works just fine.

Well probably it is on the backend side (LDAP)  - not delivering in time. Thanks for your insight.
