### ISSUE TITLE
[Request] Setting up to add " target ='blank' " in External Pages

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/external#215]
### Steps to reproduce
1. Install External Sides App
2. add a external Side
3. Klick on a external Side

### Actual behaviour
move fully the Nextcloud away because it open's in a own windows, 
like the target="_self" and therewith if working with a single Windows
disappears the users actual opened NextCloud webpage and open
the External Webpage in the own Browser Window

### Expected behaviour / Improvement
Tell us what should happen:
Pop out or pop in a Tab of the Browser (like it is configured in the browser) to have a extended Window 
and hold open/ keep/have ready still the Nextcloud and not fully disappear. 
and therewith add by User External Config (or the user or global External app Config)

Actual Picture : 
https://apps.nextcloud.com/apps/external

Solution Example:
![admin-settings](https://user-images.githubusercontent.com/7925717/93734070-1b6f2d00-fbd8-11ea-8ffb-92f3997b817b.png)

this could be the solution of 
**_![Open in new tab](https://github.com/nextcloud/external/issues/79)_**

and please no other discussions, only if it good or not good,
a discussion dilutes this issue only

thumps up or thumps down

and Nickvergessen, it should really leave it to the administrator or the user how they want/should it to be opened in the browser, easy to say use a extra key shortcuts is not really intelligent.. because we walk in the web with a Browser and not any is so an "crack" like you in key shortcuts. And in a Company office of a Factory disturbs massively if the nextcloud suddenly away.
Also in private way...

best regards
Blacky

blackysgate.de

### Server configuration

**Fedora 32**:

**Web server: actual server in Fedora**

**Database: MariaDB**

**PHP version: Actual Fedora 32 Repo**

**Comment by jancborchardt** [comment]
Duplicate of https://github.com/nextcloud/external/issues/79#issuecomment-604733286 – see my comment and do not open further issues on this please.
