### ISSUE TITLE
icon color error

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/external#216]
hi we can use dark theme or not.
Buy when we upoad a picture this picutre is negativ mode...

Image created by nextcloud
![image](https://user-images.githubusercontent.com/38983960/94270736-d54ffb80-ff40-11ea-8e4c-476076866a5b.png)

Original image 
![image](https://user-images.githubusercontent.com/38983960/94270775-e862cb80-ff40-11ea-9b4c-7921ecf0a7bc.png)

We also try : 
![image](https://user-images.githubusercontent.com/38983960/94270843-02041300-ff41-11ea-83ba-4c27551d1e14.png)

Theming bug

![image](https://user-images.githubusercontent.com/38983960/94270891-1b0cc400-ff41-11ea-96ba-3990cf81ceca.png)

Can you help me

**Comment by nickvergessen** [comment]
Colored icons are not supported by Nextcloud atm.
The inverting on the header is controlled by the primary color (white in your case?) and not the bright/dark mode setting.

**Comment by nickvergessen** [comment]
Closing as per above
