### ISSUE TITLE
Infinite Loading Circle - Nothing happens when clicking on "New Site"

### ISSUE THREAD

**Issue by edelrost** [nextcloud/external#217]
### Steps to reproduce
Try to add new site, button does nothing, infinite loading circle
Was working fine in NC19.

### Expected behaviour
Adding of new site

### Actual behaviour
Nothing happens

## Server configuration detail

**Operating system:** Linux 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** sqlite3 3.22.0

**PHP version:** 

7.4.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, propro, raphf, iconv, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gender, gettext, gmp, htscanner, http, imagick, imap, intl, json, ldap, mailparse, exif, mongodb, mysqli, OAuth, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, shmop, SimpleXML, soap, SourceGuardian, sqlite3, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, ionCube Loader

**Nextcloud version:** 20.0.0 - 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - apporder: 0.11.0
 - bookmarks: 3.4.1
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - encryption: 2.8.1
 - external: 3.7.0
 - federatedfilesharing: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - gpxpod: 4.2.3
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.5.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - passwords: 2020.10.0
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - activity
 - admin_audit
 - federation
 - files_external
 - firstrunwizard
 - richdocuments
 - spreed
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "muninn.thomaskirsten.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "20.0.0.9",
    "overwrite.cli.url": "https:\/\/muninn.thomaskirsten.com",
    "installed": true
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Tested on Vivaldi and Edge

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
/
```
</details>

<details><summary>Nextcloud log</summary>

```
/
```
</details>

<details><summary>Browser log</summary>

/
</details>

**Comment by andresgongora** [comment]
Probably related. External sites I had set up previously still work, but I can not longer edit them as the loading circle never goes away (see screenshot). Also, I am unable to see the Icons' selection (same screenshot) which appeared at the bottom. 

I've disabled all other apps, reset the server (on Apache/Linux) and started a fresh browser. 

![image](https://user-images.githubusercontent.com/12051510/95318399-cc432080-0896-11eb-988f-efd7fac6e453.png)

**Comment by nickvergessen** [comment]
Okay, I figured it now. I had build the package but forgot to compile the javascript before.
3.7.1 with built JS is now in the appstore.

**Comment by Erebus999** [comment]
Unfortunately the same error with the 3.7.1 version

**Comment by skvl** [comment]
The issue still relevant with NC21 and app 3.8.1:
![изображение](https://user-images.githubusercontent.com/20656851/111638153-21526d80-880b-11eb-887c-b1637c45a81b.png)

CC @nickvergessen
