### ISSUE TITLE
https sites that doesnt allow embedding - new feature needed. - enhancement

### ISSUE THREAD

**Issue by pbt39ppc** [nextcloud/external#219]
### Steps to reproduce
1. add site with https
2. try to click on link 
3. if `Redirect This site does not allow embedding` was checked, site is opens in the same window 

### Expected behaviour
Need one more checkbox: `Open in new tab/window` that will add `target="_blank"` to that link

**Comment by nickvergessen** [comment]
See #79

**Comment by pbt39ppc** [comment]
Use right click and open new tab is the workaround. users dont know is the site should be opened in new tab, its not a problem for users with some skills. But for users that is not experienced enough, that could be a problem, so the solution is to force add target blank
