### ISSUE TITLE
Memory leak due to endless GET-Loop loading menu svg's

### ISSUE THREAD

**Issue by Ornias1993** [nextcloud/external#225]
### Steps to reproduce
1. Try adding a lot of sites, with LDAP and "Custom Menu" apps enabled
2. Notice slowdown after every site
3. Notice after 3-4 sites  it mostly just freezes
4. continue till you get a complete freeze (even on reload of the page) and SBOX_FATAL_MEMORY_EXCEEDED

### Expected behaviour
You should just be able to add sites

### Actual behaviour
A memory leak, due to endlessly loading site resources as soon as a group selection dropdown.
We are talking: thousands(!) of requests in minutes
It seems to GET-loop the menu SVG's, more precisely: The SVG's in the top menu (not Custom Menu)

### Server configuration
Docker, LDAP user backend, "Custom Menu" plugin

**Operating system**:
Debian 10

**Web server:**
Apache

**Database:**
MariaDB (latest)

**PHP version:**
Docker integrated

**Nextcloud version:** (see Nextcloud admin page)
20.0.1

**Where did you install Nextcloud from:**
Dockerhub

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - external: 3.7.1
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - groupfolders: 8.1.0
  - integration_github: 0.0.10
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.19.1
  - spreed: 10.0.1
  - systemtags: 1.10.0
  - tasks: 0.13.5
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - support
  - survey_client
```

**Nextcloud configuration:**
```
{
    "system": {
        "overwrite.cli.url": ""***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            ""***REMOVED SENSITIVE VALUE***,
            ""***REMOVED SENSITIVE VALUE***",
            ""***REMOVED SENSITIVE VALUE***",
            ""***REMOVED SENSITIVE VALUE***",
            ""***REMOVED SENSITIVE VALUE***",
            ""***REMOVED SENSITIVE VALUE***",
            ""***REMOVED SENSITIVE VALUE***"
        ],
        "defaultapp": "dashboard",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": ""***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": 0,
        "logrotate_size": "104847600",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "***REMOVED SENSITIVE VALUE***
        },
        "htaccess.RewriteBase": ""***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": ""***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": ""***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "data-fingerprint": ""***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```
### Client configuration
**Browser:**
Chrome (latest, auto update)

**Operating system:**
Windows 10 (latest, auto update)

#### Nextcloud log (data/owncloud.log)
```
Nothing relevant seen, needs some more work if I have the time to printout a debug
```

#### Browser log
Endless loading of site resources (like a endless reload in the background going on), nothing related to any plugin (warning, info or error)

**Comment by Ornias1993** [comment]
Update:
GET-Loop of menu svg's starts when the "check" bar besides a new site, turns green for the first time.

**Comment by nickvergessen** [comment]
Works fine here, but maybe @simmstein can enlighten us if something would be wrong with calling `OC.Settings.Apps.rebuildNavigation()`

**Comment by Ornias1993** [comment]
@nickvergessen Interesting, it could also be related to the "Custom Menu" plugin, did you happen to test with or without that one?

**Comment by nickvergessen** [comment]
I tested with and without that, but it worked quite nice in both situations

**Comment by simmstein** [comment]
If the selected display of custom menu is "Side menu" or "Always displayed" and when the top menu (DOM of #appmenu) is updated then the menu is updated too : https://gitnet.fr/deblan/side_menu/src/branch/master/src/SideMenu.vue#L146-L152 (AppOrder compatibility).

In case of apps that must be displayed on the top, the function `updateTopMenu` is run every 50ms. It manages external sites and apps (and targets) : https://gitnet.fr/deblan/side_menu/src/branch/master/templates/js/_topMenuApps.js

**Comment by Ornias1993** [comment]
> If the selected display of custom menu is "Side menu" or "Always displayed" and when the top menu (DOM of #appmenu) is updated then the menu is updated too : https://gitnet.fr/deblan/side_menu/src/branch/master/src/SideMenu.vue#L146-L152 (AppOrder compatibility).
> 
> In case of apps that must be displayed on the top, the function `updateTopMenu` is run every 50ms. It manages external sites and apps (and targets) : https://gitnet.fr/deblan/side_menu/src/branch/master/templates/js/_topMenuApps.js

Interesting thing is the reload loop is only the svg's from the TopMenu, not the SVG's in the Custom "side menu", So i don't think updateTopMenu is the thing causing this, because if that would've been the trigger SideMenu would've triggerd too, right?...

**Comment by simmstein** [comment]
Btw, if the menu does not change, I implemented a "cache" mechanism: https://gitnet.fr/deblan/side_menu/src/branch/master/templates/js/_topMenuApps.js#L17-L21

Is it possible to record your screen to understand what happen?

**Comment by simmstein** [comment]
> Interesting thing is the reload loop is only the svg's from the TopMenu, not the SVG's in the Custom "side menu", So i don't think updateTopMenu is the thing causing this, because if that would've been the trigger SideMenu would've triggerd too, right?...

1) The top menu is generated by the hard way (php generates html)
2) The side menu is generated using the top menu
3) In case of top apps defined in the custom menu settings, every 50ms, the function regenerates the menu if it changed (its innerHTML is different than the previous execution, eg: window was resized or AppOrder was applied).

At the same time, if #appmenu is updated then the side menu panel is updated too without applying modifications to the top menu.

**Comment by Ornias1993** [comment]
Okey, some more test info:
It only happens on Chrome, not on firefox.
I also tried in an incognito browser without extentions (to rule out any extentions messing with things).

Chrome version is:
86.0.4240.111

I think the screenshot is clear enough
<img width="343" alt="svgloop" src="https://user-images.githubusercontent.com/7613738/97880646-b6a00a00-1d21-11eb-9ec5-4dc0d7277c27.PNG">

**Comment by simmstein** [comment]
What apps are available in the side menu? 
What apps are available in the top menu?

In you screenshot, there are `mail`, `app` (standard icon) and `calendar`.

**Comment by Ornias1993** [comment]
Click 1:
<img width="411" alt="icons" src="https://user-images.githubusercontent.com/7613738/97888197-2a92e000-1d2b-11eb-86a7-a85e91ce4487.PNG">

Click 2 (+a bunch of external apps with svg icons)
<img width="183" alt="icons 2" src="https://user-images.githubusercontent.com/7613738/97888258-41393700-1d2b-11eb-9e44-2fb09d394207.PNG">

**Comment by nickvergessen** [comment]
I still can not reproduce this, even with the side_menu app enabled :(

**Comment by Ornias1993** [comment]
I'll try to look into it again this week... Thanks for the effort anyway! :)
