### ISSUE TITLE
Android App does not open as external Site 

### ISSUE THREAD

**Issue by weinic** [nextcloud/external#231]
On click by this

![Screenshot_20201217-121839__01](https://user-images.githubusercontent.com/57099502/102484097-06365d00-4066-11eb-8cd0-0d7d741e2039.jpg)

Comes the following Error

![Screenshot_20201217-121853](https://user-images.githubusercontent.com/57099502/102484120-12221f00-4066-11eb-9e25-450b694156a9.jpg)

**Comment by nickvergessen** [comment]
well tg: is not a valid URL?

**Comment by weinic** [comment]
This is the URL I entered. 
I don't know why only tg: is called.

![Uploading Screenshot_20201217-163845__01.jpg…]()

**Comment by nickvergessen** [comment]
cc @tobiasKaminsky any idea?

**Comment by tobiasKaminsky** [comment]
Android refreshes this every 10th opening of the app.
Maybe it just showed outdated data?

**Comment by weinic** [comment]
Hello @all
i just installed the latest NC client, now the redirect to telegtam works.

Thanks a lot
