### ISSUE TITLE
Cannot administer external sites

### ISSUE THREAD

**Issue by escribana** [nextcloud/external#234]
### Steps to reproduce
1. Open settings for external sites as admin
### Expected behaviour
Info of already installed sites and new input fields should show up
### Actual behaviour
No info displayed, only eternal spinning wheel
![ExternalSitesError](https://user-images.githubusercontent.com/28783957/105403389-00193a80-5c29-11eb-815c-e92ecc2d2cde.png)
### Server configuration
**Operating system**: Ubuntu 20.04 LTS
**Web server:** Apache/2.4.41 (Ubuntu)
**Database:**mysql  Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))
**PHP version:**PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
**Nextcloud version:** 21.0.0.beta3
**Where did you install Nextcloud from:**
Official download
**List of activated apps:**
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.1.3
  - checksum: 1.0.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.3
  - contactsinteraction: 1.2.0
  - customproperties: 1.0.1
  - dashboard: 7.1.0
  - dav: 1.17.1
  - external: 3.8.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_linkeditor: 1.1.3
  - files_pdfviewer: 2.1.0
  - files_readmemd: 1.2.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 8.2.0
  - guests: 1.6.2
  - impersonate: 1.8.0
  - login_notes: 0.3.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.8.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.6.3
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - registration: 0.6.0
  - richdocuments: 3.7.11
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.0.0-alpha.3
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.escriban.ch",
            "45.76.89.170",
            "collabora.escriban.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.0.10",
        "overwrite.cli.url": "http:\/\/45.76.89.170\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "CH",
        "skeletondirectory": "",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "external",
            "calendar",
            "spreed",
            "registration",
            "groupfolders",
            "customproperties",
            "impersonate",
            "files_linkeditor",
            "polls",
            "files_readmemd",
            "login_notes",
            "metadata"
        ],
        "defaultapp": "files",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}

### Client configuration
**Browser:**
Firefox 84.02
**Operating system:**
 Ubuntu 20.04 LTS

**Comment by nickvergessen** [comment]
Did you install the app from the appstore?

**Comment by escribana** [comment]
I updated the app from within nextcloud version 20.04 (admin/apps/update). Then i switched to nextcloud 21.0.0 beta 3. Current app version is 3.8.0.

**Comment by escribana** [comment]
New info from Firefox-Webconsole:
"Die Ressource von "https://nextcloud.escriban.ch/apps/external/js/dist/admin.js?v=269fef1b-28" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff)."
More information: [https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default](url)

**Comment by nickvergessen** [comment]
Right, seems like the file is missing from the 21 release somehow

**Comment by escribana** [comment]
I copied the files from version 3.7.1 into "external/js/dist" and all is working now!

**Comment by nickvergessen** [comment]
Released a new version, to also fix the Chrome bug: #227
