### ISSUE TITLE
Show sides from other usergroups

### ISSUE THREAD

**Issue by hupling** [nextcloud/external#241]
### Steps to reproduce
Add different links for different usergourps https://<<url>>/apps/external/36
You can switch to a different link, if you change the link number. For example if you type 30 instead of 36. This is a security issue.

### Expected behaviour
Links only accessible for your usergroup.

### Actual behaviour
You can see the other side.

### Solution

Use UIDs that you can not guess.

**Comment by nickvergessen** [comment]
Can you test and confirm the fix at https://github.com/nextcloud/external/pull/244

**Comment by hupling** [comment]
Thank you. It works perfect.
