### ISSUE TITLE
{displayname} with " " in the name crashes iOS App

### ISSUE THREAD

**Issue by Wastel** [nextcloud/external#242]
### Steps to reproduce
1. Create a new external website
2. use url schema: https://xyz.host.tld/foo=bar&bar=foo&name={displayname}
3. on iOS App click on the Button/Link

If I remove the {displayname} parameter from the url everything ist working.
I suspect the " " in the displayname (e.g. "John Smith") creates an invalid URL and should be encoded.

### Expected behaviour
The page opens within the App.

### Actual behaviour
The iOS app crashes.
The Android App works normal.

## Server configuration detail

**Operating system:** Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.25

**PHP version:** 

8.0.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 21.0.1 - 21.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 18.0

**Where did you install Nextcloud from:** Web

## Client configuration

**Browser:** iOS App / WebKit

**Operating system:** iOS

**Comment by nickvergessen** [comment]
Can you test and confirm the fix at https://github.com/nextcloud/external/pull/243

**Comment by Wastel** [comment]
This fix is working. Thank you very much - and apologies for not finding the existing solution.
