### ISSUE TITLE
Grant posssibility to open an navbar token in new tab in the browser

### ISSUE THREAD

**Issue by ChrisCano66** [nextcloud/external#252]
Hello,

I am an trainee in a public structure that uses nextcloud. Their goal is to use free software and propose improvements for the free community.

In this context, I am working on improving the External module for NextCloud.
We would like to give to users the opportunity to open external links in a new tab of their browser.

To do this, we have to modify the core of NextCloud by adding an option when clicking on links in the navbar. This will allow to External to use this option and for users. However, this will give all applications a chance to do the same.

That’s why we want to ask for your permission to do it if you want it to be possible. On the other hand we would understand that your want to leave the application intuched and don't authorize the following modification for security or other reasons.

By paying attention to our request.

Thank you.

**Comment by nickvergessen** [comment]
Please see pinnged issue

**Comment by fccl-vandoeuvre** [comment]
Hello,

ChrisCano66 got the wrong project, the question should be asked on the "Nextcloud/Server" project.
That is to say in a first step to modify the core of Nextcloud.
