### ISSUE TITLE
Restrict links to groups

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/external#26]

**Comment by nickvergessen** [comment]
I guess it makes sense

**Comment by putt1ck** [comment]
We think this would be particularly useful in a education setting - all edu web stuff enabled as external sites, but each only enabled for groups of students that will find them relevant.

**Comment by olegchensky** [comment]
Yes, very interesting feature!

**Comment by adamlove86** [comment]
Agree - would be great to be able to restrict particular sites to particular groups or users. Eg some sites for students, some for admins, some for staff.
