### ISSUE TITLE
Same origin policy forbids external pages

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/external#27]
* configure https://google.com
* get following error: `Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

This is caused by https://github.com/nextcloud/server/pull/4072 because now this option is added to every request: https://github.com/nextcloud/server/blob/abe4a19cbc44b34bf171d1e9499c3e834364bd31/lib/base.php#L674-L674

@LukasReschke Any idea how to solve this? We need the external app.

**Comment by nickvergessen** [comment]
Well I guess we could also start to redirect instead of iframe. maybe as an option

**Comment by MorrisJobke** [comment]
> Well I guess we could also start to redirect instead of iframe. maybe as an option.
> Because I bet the othersite also prevents embeding

Umm ... I guess this is not the idea of having it integrated. 🙈

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by LukasReschke** [comment]
> Umm ... I guess this is not the idea of having it integrated. 🙈

This is how it is. You can't embed any page that you want to embed. The embedded page can decide whether it allows iframing or not to protect against clickjacking attacks: https://en.wikipedia.org/wiki/Clickjacking

If the site that is embedded decides to disallow embedding (which is a sane option and most will do!). If you control the embedded site you may try to configure https://en.wikipedia.org/wiki/Clickjacking#Content_Security_Policy in a way to allow embedding from your Nextcloud.
