### ISSUE TITLE
The groups are not effecting with external sites linking

### ISSUE THREAD

**Issue by kvvaradha** [nextcloud/external#270]
First of all, thank you for making a great module, its a very good module  and which helps reduce our manual works. 

And recentlly we discovered something unusal like we are trying to create some more groups and make links enabled based on groups. it works for admin groups. but for other groups it doesnt work. May i know the reason caused with this.

I tried to check in the appconfig table in the external sites url, it connected  with some data level issues, may be there is some problem in the program of saving the groups.  kindly review it again and help me to fix it. 

thank you

**Comment by nickvergessen** [comment]
Works quite nicely here.
If the problem persists, please fill out the complete issue template
