### ISSUE TITLE
Do not have open in new tab option

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/external#275]
Could you build option for opening in new tab "_blank"?
Some external sites, I want to keep orginal nextcloud. Just need to open in new tab.

**Comment by nickvergessen** [comment]
Please see the pinned ticket

**Comment by cmdntd** [comment]
How could I see the pinned ticket? 
@nickvergessen

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2021-08-31 16-53-37](https://user-images.githubusercontent.com/213943/131525614-cb5638a4-ce36-45d6-9f64-8d7febbec30a.png)


Link #79
