### ISSUE TITLE
Redirect option not opening in a new window

### ISSUE THREAD

**Issue by nollivier** [nextcloud/external#284]
Hi, 

I'm not sure if this is a issue or the expected behaviour, but when I chose the option "Redirect" for an external site in my Nextcloud, it opens it on the same window, instead of a new one (or a new tab). 

It would be useful to have the external site opening in a new window, so that the Nextcloud Hub is not closed. 

Regards,

**Comment by gary-kim** [comment]
Please see pinned issue.
