### ISSUE TITLE
[BUG] Icon color in Settings Menu inverted

### ISSUE THREAD

**Issue by MaxWaldorf** [nextcloud/external#291]
### Steps to reproduce
1. Place menu in User settings
2. Switch in default or Dark theme
3. See inverted colors

### Expected behaviour
Respect icon and dark icon according to current theme...
dark icon for white / default theme
white icon for Dark theme

### Actual behaviour
White on White
Dark on Dark

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)

22.2.6 Docker version

**Where did you install Nextcloud from:**

Docker

**Comment by nickvergessen** [comment]
Works quite fine for me using the default setting icon the app brings:
Dark | Bright
---|---
![Bildschirmfoto von 2022-04-04 11-16-53](https://user-images.githubusercontent.com/213943/161513591-bb230f6f-b1d2-4840-b2b0-5161d17b77c4.png) | ![Bildschirmfoto von 2022-04-04 11-16-40](https://user-images.githubusercontent.com/213943/161513584-19faefe7-a8b8-4670-b299-6e90f56716ab.png)

**Comment by MaxWaldorf** [comment]
![Untitled](https://user-images.githubusercontent.com/15877853/161519293-914106c1-9f01-4d86-b05f-e4bc5da9756b.png)
Here is the case for me...

**Comment by nickvergessen** [comment]
Should work when you delete the icons and only upload the dark version as sso.svg then. The menu is inverting icons automatically

**Comment by MaxWaldorf** [comment]
ok works but I have to admit this was not really natural...
SHould I upload only dark versions of icons whatever the menu?

**Comment by nickvergessen** [comment]
seems like it, yes. Only for the topbar both colors are needed
