### ISSUE TITLE
Add re-arranging of external site entries

### ISSUE THREAD

**Issue by mattkrins** [nextcloud/external#294]
### Expected behaviour
External site entries can be re-arranged/organised as needed by dragging them into position.
![drag](https://user-images.githubusercontent.com/2367602/161865954-fbe2d5a5-3157-4294-b3c2-80a50f87d8aa.gif)

### Actual behaviour
Existing external site entries must be removed/added until the desired arrangement is achieved.

**Comment by nickvergessen** [comment]
Duplicate #70
