### ISSUE TITLE
Settings menu entries looks broken

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/external#39]
Configure a "settings" menu entry:

<img width="1009" alt="bildschirmfoto 2017-06-06 um 16 33 02" src="https://user-images.githubusercontent.com/245432/26853011-eadccbf4-4ad5-11e7-992c-5903d9ba3853.png">

Then the menu looks broken.

<img width="209" alt="bildschirmfoto 2017-06-06 um 16 33 19" src="https://user-images.githubusercontent.com/245432/26853010-ead78234-4ad5-11e7-9c0a-c70b89fb2c8a.png">

@nickvergessen Wasn't this fixed in the past? Could you have a look at this?

**Comment by nickvergessen** [comment]
You have to pick a small icon, like the settings.svg

**Comment by nickvergessen** [comment]
Yeah the "external.svg" should not be used, because it is white and 32² instead of 16² and black like the "settings.svg"

> ![bildschirmfoto vom 2017-06-07 09-20-20](https://user-images.githubusercontent.com/213943/26866712-ad0f9b20-4b62-11e7-89eb-8e9686e929e8.png)

**Comment by MariusBluem** [comment]
Is there a way to check icons and prevent selecting incompatible ones? @nickvergessen

**Comment by nickvergessen** [comment]
I'm not going to start xml parsing to check for a potential size of svgs, sorry.
