### ISSUE TITLE
Feature request: Be able to publish internal sites through a php proxy script

### ISSUE THREAD

**Issue by Pammetje** [nextcloud/external#393]
Hi,

It would be awsome if it would be possible to also publish internal sites through a php proxy script
I am running nextcloud on a home server. It would be awesome if I can publish my internal IP webcams and other internal webconsoles (protected by Nextcloud authentication)

**Comment by nickvergessen** [comment]
This is out of scope for this application. It only adds entries to the top bar navigation. What you request is a multitude bigger effort.
