### ISSUE TITLE
Custom Development

### ISSUE THREAD

**Issue by coltonarmstrong** [nextcloud/external#41]
Are you available to do a customization of this for me?  If so, pm me your rates.

What I need done:

-Setup groups of links with name and icon for the group.
-Be able to move links between the different groups. Existing app links and External app links.
-Have main group stationary in the direct header menu and the other groups as the group icon with a dropdown list of links with their associated icons.

**Comment by MariusBluem** [comment]
Find out more about our Enterprise support over here: https://nextcloud.com/enterprise

If you need custom consulting/development you are welcome to contact our sales team.
