### ISSUE TITLE
allow target blank for external links

### ISSUE THREAD

**Issue by fuco809** [nextcloud/external#413]
### Steps to reproduce
1. external site links open within the nextcloud menu frame

### Expected behaviour
should open a new tab, with only external destination (not nextcloud iframe) 
target=_blank

### Actual behaviour
links to same window into a frame of the nextcloud menu

### Server configuration
NC 25.0.3
external-sites 5.0.0
custom_menu 3.5.2
theming is active
and others.

**Operating system**:
any

**Web server:**
apache 2.4.54

**Database:**
mariadb10.x

**PHP version:**
8.0

**Nextcloud version:** (see Nextcloud admin page)
25.0.3 latest

**Where did you install Nextcloud from:**
--

**List of activated apps:**
external sites
custom menu
... others ...

**Nextcloud configuration:**

### Client configuration
**Browser:**
any (chrome, edge, firefox)

**Operating system:**
windows

#### Nextcloud log (data/owncloud.log)
--

#### Browser log
--

reference : https://gitnet.fr/deblan/side_menu/issues/214 (side menu / custom menu)

**Comment by spreeni151** [comment]
Sorry for bringing this up again - but the redirect option only opens links in a blank windows when the link is configured as Position: head-menu. When it configured to be in settings menu a link is opend in the same windows and NOT in a blank tab. Is this a bug or a circumstance that cannot be changed.
Regards, Frank

**Comment by nickvergessen** [comment]
Sounds like something you can open as a bug report
