### ISSUE TITLE
Quota link feature broken in 26

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/external#457]
* Ref https://github.com/nextcloud/nextcloud-vue/pull/3958#discussion_r1158754977
* Ref https://github.com/nextcloud/server/pull/36002

### Steps to reproduce
1. Create a link with position "User quota"
![grafik](https://user-images.githubusercontent.com/213943/230160273-39fc4b1f-45f4-441e-b24e-9a786191413d.png)

### Expected behaviour
Personal settings and files app left sidebar should link to the configured page
![Bildschirmfoto vom 2023-04-05 19-39-31](https://user-images.githubusercontent.com/213943/230160415-9bda0f1e-5501-4e6f-a08e-0f810c316e0d.png)
![Bildschirmfoto vom 2023-04-05 19-39-45](https://user-images.githubusercontent.com/213943/230160418-f7f705ea-a8af-4f39-bb7b-91090580dc2d.png)

### Actual behaviour
JS magic is in place

**Comment by skjnldsv** [comment]
Ah, wasn't even aware something like that existed! :/

**Comment by provokateurin** [comment]
The link in the personal settings is still there, it's just way down the page and looks very odd. I'm not sure how it was supposed to work before and why it is broken now. In my digging I couldn't find a way to put the links directly below the quota, I assume it only worked because there weren't so many entries in the personal settings before?

**Comment by provokateurin** [comment]
The two options I see to fix this are:
1. Completely remove the external sites from the personal info page because they can't be displayed directly below the quota
2. Add a new proper section in the personal info, but accept that it's not near the quota.

**Comment by provokateurin** [comment]
![image](https://github.com/nextcloud/external/assets/26026535/1b523d4b-b5c9-4271-a8f5-526492a414e9)
in 25 it is definitely already broken
