### ISSUE TITLE
could not activate "External sites" got "server could get unstable"

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/external#47]
I got the Information from nextcloud that activating this app could get the web server unstable. But It do not tell me why.

**Comment by nickvergessen** [comment]
There should be a message in the logs

**Comment by Mannshoch** [comment]
```
Error	index	RuntimeException: image not found: image:SP-Blog.svg webroot: serverroot:/home/httpd/vhosts/server/httpdocs/next

    /home/httpd/vhosts/server/httpdocs/next/apps/external/appinfo/app.php - line 38: OC\URLGenerator->imagePath('external', 'nb-Blog.svg')
    /home/httpd/vhosts/server/httpdocs/next/lib/private/NavigationManager.php - line 64: OC_App {closure}()
    /home/httpd/vhosts/server/httpdocs/next/lib/private/legacy/app.php - line 744: OC\NavigationManager->getAll()
    /home/httpd/vhosts/server/httpdocs/next/lib/private/TemplateLayout.php - line 84: OC_App getNavigation()
    /home/httpd/vhosts/server/httpdocs/next/lib/private/legacy/template.php - line 232: OC\TemplateLayout->__construct('user', 'files')
    /home/httpd/vhosts/server/httpdocs/next/lib/public/AppFramework/Http/TemplateResponse.php - line 157: OC_Template->fetchPage()
    /home/httpd/vhosts/server/httpdocs/next/lib/private/AppFramework/Http/Dispatcher.php - line 113: OCP\AppFramework\Http\TemplateResponse->render()
    /home/httpd/vhosts/server/httpdocs/next/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
    /home/httpd/vhosts/server/httpdocs/next/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /home/httpd/vhosts/server/httpdocs/next/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /home/httpd/vhosts/server/httpdocs/next/lib/base.php - line 1010: OC\Route\Router->match('/apps/files')
    /home/httpd/vhosts/server/httpdocs/next/index.php - line 40: OC handleRequest()
    {main}
```

**Comment by nickvergessen** [comment]
Are you running Nextcloud 11 or 12?

**Comment by nickvergessen** [comment]
If 11: please upload an icon named `nb-Blog.svg` to the `apps/external/img` folder.
If 12: please delete the complete app and download the newest version from https://apps.nextcloud.com/apps/external

**Comment by Mannshoch** [comment]
nextcloud 12. did not work. 
I inserted `nb-Blog.svg` to `apps/external/img` same effect.
I removed `apps/external/img` and tryed to install it again. Same error.
Again I added a `nb-Blog.svg` to `apps/external/img` same effect again.

**Comment by nickvergessen** [comment]
Well in the nextcloud 12 from my link the code that is mentioned in your stacktrace above does not exist. So there should at least be a different error now.

**Comment by Mannshoch** [comment]
no it's the same error. not a bit had changed. 
As far I remember, these svg was a part of an external link I had in the days I started my site with Owncloud 7. I used this app only for some experiments and removed it again. I do not anymore need this svg and it also do not exist anymore ( for the tests, renamed a random svg and copied it to `apps/external/img` )

If I search in phpMyadmin for these SVG I got search results at following position:
4 in oc_activity
1 in oc_appconfig
4 in oc_filecache

**Comment by nickvergessen** [comment]
It can not be the same, because in the Nextcloud 12 version, the code in question does not exist anymore. Also in 12 there is fallback code, so when an image does not exist, it uses the default image instead. Please delete all the code from apps/external/ and redownload the app manually from the appstore.
