### ISSUE TITLE
Downloads from external app not possible

### ISSUE THREAD

**Issue by poVoq** [nextcloud/external#48]
### Steps to reproduce
1. Install a local copy of RAWGraphs ( http://app.rawgraphs.io/ )
2. Embed as external page
3. Try to download created graph via the "download" button (in Firefox)

### Expected behaviour
Should open a "safe as" browser popup

### Actual behaviour
Nothing happens.

### Server configuration

**Operating system**:
Ubuntu
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0

I guess this is a intended security feature, but is there any way this could be enabled?

**Comment by nickvergessen** [comment]
I dont think so. It's your browser protecting you, or their server protecting them. Not Nextcloud

**Comment by poVoq** [comment]
I don't think its that simple. I checked with Chome and it downloads the files fine (as both sides run on the same domain).

It seems a specific CSP issue with Firefox. Maybe there is a need to whitelist blob downloads in the header of the Nextcloud page for child iframes?
