### ISSUE TITLE
Getting around  'X-Frame-Options' to 'sameorigin' by offering option to open link in new tab

### ISSUE THREAD

**Issue by rubella** [nextcloud/external#49]
I'm using NextCloud as a dashboard for all of my self-hosted software (~15 'external' links), but many of them don't work because of the 'X-Frame-Options' to 'sameorigin' directive. 

Would it be possible to instruct some of the external links to open in a new tab or even to add this as a feature in an upcoming release?

Perhaps an additional dropdown with an option for 'iframe, new tab or new window'?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/external/pull/43
