### ISSUE TITLE
Run as defaultApp

### ISSUE THREAD

**Issue by MichaelBarth** [nextcloud/external#50]
Steps to reproduce
1. Write defaultapp=>external ib config.php
2. Try to login

I Think its a routing problem.
After login the URL should be something like external/1  but it is external/  thats the Problem

**Comment by nickvergessen** [comment]
Yeah well this app just does not support to be a default app, because it doesn't have a frontpage

**Comment by MichaelBarth** [comment]
Thank you for your response! I need the url with external/1 as frontpage.

Is it possible? I really need that feature!
I tried this:

['name' => 'page#showPage', 'url' => '/{id}', 'verb' => 'GET', 'defaults' => array('id' => 1)]

But it is not working

Thank you very much!
Michael

**Comment by MichaelBarth** [comment]
Found a solution!

'routes' => [
		['name' => 'page#showPage', 'url' => '/{id}', 'verb' => 'GET', 'defaults' => array('id' => 1)],
		['name' => 'page#showPage', 'url' => '/', 'verb' => 'GET', 'defaults' => array('id' => 1)],
is working 4 me

**Comment by nickvergessen** [comment]
Well that will only work until you delete the first page at any later time, then ID 1 will not be reused and therefor the link will be dead again...

**Comment by pirate** [comment]
FYI I fixed this in ownCloud, I'll be submitting a PR to nextcloud soon: https://github.com/owncloud/core/pull/28962
