### ISSUE TITLE
Link displayed incorrectly in settings dropdown if image is bigger than 16x16px

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/external#53]
Link is "Help123"

<img width="199" alt="screen shot 2017-09-13 at 11 34 41" src="https://user-images.githubusercontent.com/878997/30370372-b070e44c-9877-11e7-9348-1bdf37064a94.png">

**Comment by LukasReschke** [comment]
Probably because the image is 32px * 32px instead of 16x16. But this is a default image and we should just use width and height attributes here then.

**Comment by nickvergessen** [comment]
Yeah, use the settings icon ;)

but yes, I vote for hardcoding the size in the server css.

**Comment by provokateurin** [comment]
This problem no longer exists in the latest version.
