### ISSUE TITLE
FutureWish: Option for "open in new target"

### ISSUE THREAD

**Issue by xstable** [nextcloud/external#530]
Would be awesome, if you could add a field to open an external link in a new target: 

![image](https://github.com/nextcloud/external/assets/1778068/eb85e6d2-f073-440d-93be-488f0ec3f555)

Currently it's only possible to open the link in same browser-window, which replace nextcloud.

**Comment by provokateurin** [comment]
Duplicate of https://github.com/nextcloud/external/issues/79
