### ISSUE TITLE
Not working in mobile android NC app after upgrade to 27.x.x

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/external#577]
After upgrading the NC server to 27.x.x I've observed that the app is no more working at the Android NC app.
It works fine at webUI, but when trying to open the page in an Android app I do not see any changes, it just shows the main navigation page.

**Comment by provokateurin** [comment]
CC @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
![2023-11-10-082107](https://github.com/nextcloud/external/assets/5836855/9cab0f49-7777-4986-9a5b-29e81c009620)

For me it still works.

**Comment by ostasevych** [comment]
> ![2023-11-10-082107](https://user-images.githubusercontent.com/5836855/281987272-9cab0f49-7777-4986-9a5b-29e81c009620.png)
> 
> For me it still works.

So, when you click over Forum or Nextcloud links they are opened in your mobile NC client?

**Comment by tobiasKaminsky** [comment]
![2023-11-14-082230](https://github.com/nextcloud/external/assets/5836855/bbb1c6d7-0ade-428d-b0a9-93ffab289320)

Yes.
can you check your external settings?

![image](https://github.com/nextcloud/external/assets/5836855/a9e3ce18-2994-4864-a018-c44309b6d828)

**Comment by ostasevych** [comment]
That is weird. In my case, the external site works fine in web, but not in Android.

**Comment by provokateurin** [comment]
Nobody else seems to run into this issue, so closing for now.
