### ISSUE TITLE
Add please separation of users

### ISSUE THREAD

**Issue by DeAlexPesh** [nextcloud/external#59]
Thank you for app, but can you add user separation for link (by groups) ?

**Nextcloud 12.0.3**

**Comment by nickvergessen** [comment]
Duplicate of #26
Groups will come with Nextcloud 13

**Comment by DeAlexPesh** [comment]
In stable version groups no work?

**Comment by nickvergessen** [comment]
It will work in the next stable version: Nextcloud 13

**Comment by DeAlexPesh** [comment]
ok, wait for release of a stable version of the nextcloud 13..
