### ISSUE TITLE
Make it possible to have links which include the name instead of the id

### ISSUE THREAD

**Issue by oparoz** [nextcloud/external#61]
It seems the URLs use the link id as a reference to where to go.
This can create problems if you setup multiple instances and want all the links to an external website to be the same.
so, it would be great if admins could use links which include a keyword or maybe the lowercase version of the name identifier.

**Comment by nickvergessen** [comment]
Since they may not be unique, I don't really like this.

Also I don't get:
> This can create problems if you setup multiple instances and want all the links to an external website to be the same.

They never are, because your domain is already different?

**Comment by oparoz** [comment]
> Since they may not be unique, I don't really like this.

Wouldn't it be possible to have a check to prevent adding duplicates?

> They never are, because your domain is already different?

Indeed, but you know the domain in advance and can use it in scripts whereas you don't know what the id is going to be.

**Comment by nickvergessen** [comment]
Our API returns the full link... nothing else you should use.
