### ISSUE TITLE
occ command 

### ISSUE THREAD

**Issue by NextGenerationcloud** [nextcloud/external#613]
Hello I'm looking for an occ command to enter websites for a user with a name link and icons

Can somebody help me ?

**Comment by provokateurin** [comment]
There are no occ commands in this app. You could use the REST API to achieve this

**Comment by NextGenerationcloud** [comment]
Can you please help me further ^^ I'm a bit at a loss XD

I would like to enter links in external sites using the admin standard via the terminal

I have a bash script that does a full installation, so this option would be great ^^

**Comment by NextGenerationcloud** [comment]
There is really no way to do this after installing nextcloud and the app https://apps.nextcloud.com/apps/external via a script

to pass “NAME” “URL” and “icon-name” to the admin?

  sudo -u www-data php8.1 occ config:app:set external --value="URL" ???

or so ?

I also take other paths that lead to the goal ^^

THX

**Comment by provokateurin** [comment]
Another way would be modifying the database manually, but I can not provide you with help for that.

**Comment by NextGenerationcloud** [comment]
Hey, you're right, thanks, I completely forgot XD
