### ISSUE TITLE
unable to access external side links pointing to LAN resources from the Android/iOS apps

### ISSUE THREAD

**Issue by j-ed** [nextcloud/external#62]
@MorrisJobke asked me to open an issue ticket in this repository to discuss the described issue.

### Actual behavior
If you set-up external side links pointing to LAN resources, these are not accessible from the Android/iOS apps, because the apps are trying to access the sides directly.
```
Nextcloud app -> Nextcloud server
              -> External site link 1
              -> External site link 2
              -> ...
```
### Expected behavior
If you' access a web page by using an external side entry in the Android/iOS apps, access should be proxied via Nextcloud and displayed properly.

```
Nextcloud app -> Nextcloud server
              -> Nextcloud server -> External site link 1
              -> Nextcloud server -> External site link 2
              -> Nextcloud server -> ...
```

### Steps to reproduce
1. setup an external side link pointing to an intranet page on your LAN.
2. Open the Nextcloud app.
3. Select an external side link.
-> `Website not available` (for parts of a second) before it is overwritten by `Sorry Modified`.

###References
https://github.com/nextcloud/android/issues/1619#issuecomment-339924727
https://github.com/nextcloud/android/issues/1608

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.3
External app version: 2.0.3

#### Client Configuration
Android version: 7.1.2
Nextcloud app version: 2.0.0

iOS version: 11.0.3
Nextcloud for iOS version: 2.17.8.00002

#### Web server error log
Nothing special has been logged related to this problem.

#### Nextcloud app protocol
Nothing has been logged.

**Comment by nickvergessen** [comment]
Hmm, the external site app iframes (since ever) or redirects (in 13) the target page.
I don't really see us playing a proxy, that is way over the top for what this simple app wants to be and do.

My advice would be to use the device control and disable it for the devices (only view it in web)

**Comment by j-ed** [comment]
@nickvergessen Wouldn't you agree that a **discussion** usually requires more than one persons opinion, otherwise it isn't really a discussion. I would appreciate if you reopen it to collect different views from other persons too, instead of closing it instantly.

**Comment by nickvergessen** [comment]
Well not sure what you want to discuss though.
"Downloading and then providing the content" will break loading of js and css files. So they would be needed to be proxied in the same way. So we need to parse the HTML and modify URLs, etc. Simply not going to happen. There is a whole industry branch trying to figure out proxies and how to make them work.

Maybe you just install a normal proxy somewhere and make it proxy to the LAN pages.

Sorry for the bummer, but the issue can be reopened when there is someone willing to do all this work.
