### ISSUE TITLE
nextcloud and vscode

### ISSUE THREAD

**Issue by neckva** [nextcloud/external#625]
Hello, 
I have installed VSCode on Docker. I can access it in two ways, either through localhost:8443, or through code.mysite.fr. I would like to be able to access my VSCode via 'external' from anywhere, without entering a password. I see two possible solutions: either I access it from localhost:8443 without entering a password, but the issue is that it doesn't work outside my home. Or, I set a password and have Nextcloud's SSO automatically validate it, since I am already logged into my session. My goal is for VSCode to appear as any other native Nextcloud application when accessed via 'external'. Does this seem possible? 
Thank you.

**Comment by provokateurin** [comment]
You would need some kind of SSO in case you don't want to enter a password, but I'd suggest you just enter another password as that is much easier than setting um any SSO.
