### ISSUE TITLE
Feature Request: Add option to not embed, but open link

### ISSUE THREAD

**Issue by daniel-wtd** [nextcloud/external#65]
Currently some Options prevent the usage of external sites.
A very easy way to have at least a workaround for this, could be to have an option, which is not embedding the site, but links to it.

### Steps to reproduce
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/external_sites.html
Describes why some sites are not working in the bottom section.

### Expected behaviour
During the creation of an external site, one should choose between "embed" and "link".
When choosing "embed" the behaviour is as known.
When choosing "link" the new link will open in a new tab or window.
Optional: links should be marked as "external" in some way.

### Actual behaviour
Most sites with X-Frame-Options or Content-Security-Policy are not usable at all.
Linking to external sites seems not possible.

### Server configuration
**Nextcloud version:** 12.0.3

**Comment by nickvergessen** [comment]
This was implemented for Nextcloud 13 already #43

**Comment by daniel-wtd** [comment]
Oh, cool. Thanks Slot :)

**Comment by RHuehne** [comment]
Could there be an option to open external sites which can't be embedded in a new tab or window instead of opening the page in the current window?

**Comment by nickvergessen** [comment]
#79
