### ISSUE TITLE
Types of links

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/external#7]
The admin should be able to add links to the settings menu as well

Suggestion is:
* link (current)
* settings (right side menu)
* quota (?)

**Comment by mario** [comment]
👍  from my side.

**Comment by marinofaggiana** [comment]
Settings ?

**Comment by nickvergessen** [comment]
web UI has left menu (links/apps) and right menu (settings/personal/admin/user/help....)

**Comment by marinofaggiana** [comment]
ah, ok

**Comment by MorrisJobke** [comment]
@rullzer Also needed in the client or do we there hardcoded URLs for now?

**Comment by rullzer** [comment]
Hardcode

**Comment by e-alfred** [comment]
Please add this information to the documentation.

**Comment by nickvergessen** [comment]
I renamed "type" to "Position" for the next release and also adjusted the names:
* Header
* Settings menu
* User quota

Do they still need more explanation in the docs?

**Comment by e-alfred** [comment]
Thanks, that makes it far more clear.
