### ISSUE TITLE
Advice on using External Sites for outside network access to Nextcloud

### ISSUE THREAD

**Issue by greavette** [nextcloud/external#72]
Hello,

I'm hoping advice can be provided on how I can solve an issue I'm having with External sites when accessing Nextcloud from outside our network.

I've installed within our network a Nextcloud Server and a Guacamole (remote access) server.  From within my network I can connect to our Guacamole server from the Nextcloud External Sites icon with no issues as we have the Guacamole server using https through reverse proxy (from our Nethserver).

Problem occurs though when I login to our Nextcloud from outside our network.  The Guacamole External Sites will not load.  The error I'm seeing is:

<IP of Guacamole> took too long to respond

Do you have any advice on how to access an external site link from Nextcloud when accessing Nextcloud from outside our network?  From within our network it works fine.  I suspect this is a DNS issue or timeout issue.

Any advice you can provide would be greatly appreciated.

Thank you.

**Comment by nickvergessen** [comment]
The external sites app is not a proxy or anything like that.
It can only IFrame or redirect to the given pages.
