### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by CSchaefer70** [nextcloud/external#77]
I installed without issue and runs. {Nextcloud 12.0.5, MySQL, php7}.
My interface looks different with less options.
Is it possible to have an option to log into the external site.  I'm using both Joomal3 and NextCloud 12.0.5 and want to be able to have just one login.

My URL = https://gbranlaw.com/nxtcld2018/index.php/login

![image](https://user-images.githubusercontent.com/26978180/35891566-02a44f38-0b73-11e8-8461-9a46d2914906.png)

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Please update to the latest version
