### ISSUE TITLE
No more anpg icon with the 3.1.0 version

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/external#83]
Can you integrate in your next version the apng icon please ?
With the old version (before version 3.0.0) i could seen my animated icon on nextcloud for my external site...
Thanks,

**Comment by nickvergessen** [comment]
Hu? Sorry I don't understand what you mean. You can upload icons in the admin settings now. and as long as they are images with 16*16, 24*24 or 32*32 size, it should work.

**Comment by Ludovicis** [comment]
Thanks, i know than i can upload icon or images with 16*16, 24*24 or 32*32 size in the admin settings... And it work. But how can i to make a apng (PNG Animated) with all this resolution ? I don't think it's possible. With my previous version((before version 3.0.0, maybe the 2.6.0), your external app don't check all this resolution, it was more easy to import picture (Gif also)

**Comment by nickvergessen** [comment]
So you get an error while uploading?

**Comment by Ludovicis** [comment]
I redid tests with images gif 32x32 and the test worked. Also sorry for this issue, i close this issue. Maybe that don't work with png animated icon... But it's not a problem if it's that work with gif image. thanks for your help nickvergessen
