### ISSUE TITLE
External sites disabled due to compatibility issue with Nextcloud 13

### ISSUE THREAD

**Issue by kukulin** [nextcloud/external#84]
<!--
After upgrading Nextcloud to v13  "external sites app" is disabled and can not be enabled with follwing error : 
App "External sites" cannot be installed because it is not compatible with this version of the server.

### Steps to reproduce
1.  Upgrade nextcloud via web interface to latest version
2. Click enable under external sites app in app manager
3.

### Expected behaviour
App "External sites should became enabled and my external sites should be available in main menu

### Actual behaviour
App not start, links are not available

### Server configuration
<!--

**Operating system**: Ubuntu in LXC container on ARM router

**Web server:** Apache 2.4.18

**Database:** Mysql 5.7.19

**PHP version:**  7.0.22

**Nextcloud version:** 13.0.0

**Where did you install Nextcloud from:** Update from builtin interface

**List of activated apps:** 

Enabled:                                                                                                                                                       
  - activity: 2.6.1                                                                                                                                            
  - audioplayer: 2.2.5                                                                                                                                         
  - bookmarks: 0.10.1                                                                                                                                          
  - bruteforcesettings: 1.0.3                                                                                                                                  
  - calendar: 1.6.0                                                                                                                                            
  - comments: 1.3.0                                                                                                                                            
  - contacts: 2.1.2                                                                                                                                            
  - dav: 1.4.6                                                                                                                                                 
  - deck: 0.3.0                                                                                                                                                
  - federatedfilesharing: 1.3.1                                                                                                                                
  - federation: 1.3.0                                                                                                                                          
  - files: 1.8.0                                                                                                                                               
  - files_pdfviewer: 1.2.0                                                                                                                                     
  - files_sharing: 1.5.0                                                                                                                                       
  - files_texteditor: 2.5.1                                                                                                                                    
  - files_trashbin: 1.3.0                                                                                                                                      
  - files_versions: 1.6.0                                                                                                                                      
  - files_videoplayer: 1.2.0                                                                                                                                   
  - firstrunwizard: 2.2.1                                                                                                                                      
  - gallery: 18.0.0                                                                                                                                            
  - logreader: 2.0.0                                                                                                                                           
  - lookup_server_connector: 1.1.0                                                                                                                             
  - mail: 0.7.10                                                                                                                                               
  - nextcloud_announcements: 1.2.0                                                                                                                             
  - notifications: 2.1.2                                                                                                                                       
  - oauth2: 1.1.0                                                                                                                                              
  - passman: 2.1.4                                                                                                                                             
  - password_policy: 1.3.0                                                                                                                                     
  - provisioning_api: 1.3.0                                                                                                                                    
  - serverinfo: 1.3.0                                                                                                                                          
  - sharebymail: 1.3.0                                                                                                                                         
  - survey_client: 1.1.0                                                                                                                                       
  - systemtags: 1.3.0                                                                                                                                          
  - theming: 1.4.1                                                                                                                                             
  - twofactor_backupcodes: 1.2.3                                                                                                                               
  - updatenotification: 1.3.0                                                                                                                                  
  - workflowengine: 1.3.0                                                                                                                                      
Disabled:                                                                                                                                                      
  - admin_audit                                                                                                                                                
  - direct_menu                                                                                                                                                
  - drawio                                                                                                                                                     
  - encryption                                                                                                                                                 
  - external                                                                                                                                                   
  - files_external                                                                                                                                             
  - tasks                                                                                                                                                      
  - user_external                                                                                                                                              
  - user_ldap

**Comment by nickvergessen** [comment]
Please install the latest version from the app store
