### ISSUE TITLE
Feature Request: ED25519 SSH-Keypairs

### ISSUE THREAD

**Issue by TalusUnheil** [nextcloud/external#85]
Hey there!

I'm changing all my servers from RSA to ECC (ED25519) SSH-Keypairs. I hope NC will support it soon, so I can switch my file server too. Thanks in advance! <3

**Comment by nickvergessen** [comment]
This is not the right place for your question. Please ask for help in the forum

**Comment by didierm** [comment]
For reference purposes : https://github.com/nextcloud/server/issues/21373

**Comment by nickvergessen** [comment]
Exactly that is the right place. 👍

This app here is about external page entries in the topbar, not about storage
