### ISSUE TITLE
Customized svg icon are not displayed

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/external#87]
### Steps to reproduce
1. Create a new external link
2. Upload bug.svg
3. Select bug.svg as icon of new link (Source : https://use.fontawesome.com/releases/v5.0.8/svgs/solid/bug.svg)

### Expected behaviour
The bug.svg should be visible in the appbar

### Actual behaviour
Only the name of the external link is displayed :(

[bug.zip](https://github.com/nextcloud/external/files/1832819/bug.zip)

**Comment by nickvergessen** [comment]
Just tested with that image and it works fine here.
