### ISSUE TITLE
Security problem with url parameters

### ISSUE THREAD

**Issue by MichaelBarth** [nextcloud/external#88]
Hi,
would it be possible to encrypt the url-parameters, so that you cannot see the userid in the source-code of the iframe?

The user has to enter a salt and a password, so he can decrypt the url-parameter later in his php script.

**Comment by nickvergessen** [comment]
That makes no sense to me.

**Comment by MichaelBarth** [comment]
Hi,
I have written a php script, that shows data from a database depending on the userid. I don't want, that the users can see the data from the other users. Without encrypting the userID in the URL It is very easy to find the link in the iframe and replace the userid manually. 
... what should I do???
