### ISSUE TITLE
using uid in url

### ISSUE THREAD

**Issue by MichaelBarth** [nextcloud/external#90]
Hi, 
it is a really great thing, that it is possible to pass the uid with the url. So I can deliver some user-related data from my data-base using the uid.

 **BUT**

Everyone can copy the external link from inside the browser by using the development-features and replace the own uid by the one of another person. Now, you can see the pages of everyone else you know the uid. That is, I do not want to be possible...

I was thinking about the idea passing the session_id and then start the session in my script, but the session_data is also encrypted, so I would not be able to handle it.

My idea of encrypting the uid was dismissed "that makes no sense". Why?

Thank you for answering!

Michael

**Comment by nickvergessen** [comment]
You have to check the session/logged in status on your site.
We will not add encryption for user ids, you could still loop over all users it just takes longer to guess...
What you plan here is https://en.wikipedia.org/wiki/Security_through_obscurity
