### ISSUE TITLE
Request : open non-framed website on a new tab

### ISSUE THREAD

**Issue by tpape** [nextcloud/external#92]
Hi ! Many thanks for the app :).
What do you think about opening non-framed websites in a new tab instead of the same one ? It can be a default behaviour or a parameter in the configuration...

I don't think it's complicate to add to the project, if I can get some free time I will study your code.

Best regards,
Thomas

**Comment by nickvergessen** [comment]
Duplicate https://github.com/nextcloud/external/issues/86
